// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzpVszSxgLApqQ83JYMGNmHirbglQ5TSk',
    appId: '1:689250158236:android:fc9d37d0c50db5ad8e0f59',
    messagingSenderId: '689250158236',
    projectId: 'match-maker-6a725',
    storageBucket: 'match-maker-6a725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUoYMAj2sHKm6A2NE3V3tI95HZ3tqMn4',
    appId: '1:689250158236:ios:0c4a410326d9081b8e0f59',
    messagingSenderId: '689250158236',
    projectId: 'match-maker-6a725',
    storageBucket: 'match-maker-6a725.appspot.com',
    androidClientId: '689250158236-aj8f15nqg40vl1lqf6lm2vrtm1tbo44g.apps.googleusercontent.com',
    iosClientId: '689250158236-kg7m7bgh5cvgn5f0ibbnv91jcd04cucc.apps.googleusercontent.com',
    iosBundleId: 'com.example.matchMaker',
  );
}
